# This is a basic workflow to help you get started with Actions

name: Run weekly report

# Controls when the workflow will run
on:
  # schedule:
  # - cron: '*/5 * * * *' # Every 5 minutes

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  run_weekly:
    runs-on: ubuntu-latest
    environment: main
    env:
      ELASTICSEARCH_URL: ${{ secrets.ELASTICSEARCH_URL }}
      ELASTIC_API_KEY: ${{ secrets.ELASTIC_API_KEY }}
      GITHUB_TOKEN: ${{ github.token }}
    steps:
    - name: Check out the repository to the runner
      uses: actions/checkout@v4  
    - name: Run
      run: ./bin/run_weekly
